Repository open-sauced/app, pull requests merged in 2022-12, with the labels that each got.

#690 feat: filter recent contributions array by last updated time
  components/molecules/ContributorTable/contributor-table.tsx
  components/molecules/LatestPrTableRow/latest-pr-table-row.tsx
Labels: requested changes

#709 fix: overflow x bug on dashboard
  components/organisms/ToolList/nav.tsx
  layouts/filter.tsx
Labels: awaiting review

#736 feat: Filter dashboard scatter plot by PR states
  components/atoms/ToggleGroup/toggle-group.tsx
  components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
  components/organisms/Dashboard/dashboard.tsx
Labels: ready-to-merge
