Repository open-sauced/app, pull requests merged in 2023-03, with the labels that each got.

#926 feat: remove default user bio
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  pages/user/[username].tsx
Labels: requested changes

#918 feat: append sub nav url and redirect to contributions if there is no highlights
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  pages/user/[username]/contributions.tsx
  pages/user/[username]/highlights.tsx
  pages/user/[username]/index.tsx
Labels: needs-response

#959 fix: keep initial user settings data after being fetched
  components/organisms/UserSettingsPage/user-settings-page.tsx
  lib/hooks/useFetchUser.ts
Labels: ready-to-merge

#967 refactor: update non connect user avatar
  components/atoms/Avatar/avatar.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: awaiting review

#960 feat: make the entire insight page buttons clickable
  components/molecules/InsightRow/insight-row.tsx
Labels: requested changes

#958 feat: add search to the create insights page
  components/atoms/Search/search.tsx
  components/organisms/InsightPage/InsightPage.tsx
Labels: awaiting review

#962 feat: add custom tooltip to pr list icon
  components/molecules/CardProfile/card-profile.tsx
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/molecules/LatestPrTableHeader/latest-pr-table-header.tsx
Labels: ready-to-merge

#957 feat: implement highlight's permanent link
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/Dialog/dialog.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/useFetchAllHighlights.ts
  lib/hooks/useFetchHiglightRepos.ts
  lib/hooks/useFetchSingleHighlight.ts
  lib/hooks/useFetchUserHighlights.ts
  pages/feed/[id].tsx
  pages/feed/index.tsx
Labels: awaiting review

#963 feat: Add delete highlights implementation
  components/molecules/AlertDialog/alert-dialog.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  lib/hooks/deleteHighlight.ts
  npm-shrinkwrap.json
  package.json
Labels: ready-to-merge

#951 fix: update local time option from user settings
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: needs-approval

#966 feat: add official logos for pre-defined topics.
  components/molecules/FilterHeader/filter-header.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  img/topicThumbnails/ai.svg
  img/topicThumbnails/c.svg
  img/topicThumbnails/cpp.svg
  img/topicThumbnails/csharp.svg
  img/topicThumbnails/java.svg
  img/topicThumbnails/javascript.svg
  img/topicThumbnails/ml.svg
  img/topicThumbnails/php.svg
  img/topicThumbnails/python.svg
  img/topicThumbnails/react.svg
  img/topicThumbnails/ruby.svg
  img/topicThumbnails/typescript.svg
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
  pages/start.tsx
Labels: requested changes

#996 feat: add pagination component to feeds and profile
  components/molecules/PaginationResults/pagination-result.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/Repositories/repositories.tsx
  pages/_app.tsx
  pages/feed/index.tsx
  stories/molecules/pagination-result.stories.tsx
Labels: awaiting review, needs-approval

#995 feat: add golang language topic to supported interests
  components/atoms/LanguagePill/LanguagePill.tsx
  img/topic-thumbnails/ai.svg
  img/topic-thumbnails/c-plus.svg
  img/topic-thumbnails/c-sharp.svg
  img/topic-thumbnails/c.svg
  img/topic-thumbnails/golang.svg
  img/topic-thumbnails/java.svg
  img/topic-thumbnails/javascript.svg
  img/topic-thumbnails/machine-learning.svg
  img/topic-thumbnails/php.svg
  img/topic-thumbnails/python.svg
  img/topic-thumbnails/react.svg
  img/topic-thumbnails/ruby.svg
  img/topic-thumbnails/rust.svg
  img/topic-thumbnails/typescript.svg
  img/topicThumbnails/ai.svg
  img/topicThumbnails/c.svg
  img/topicThumbnails/cpp.svg
  img/topicThumbnails/csharp.svg
  img/topicThumbnails/java.svg
  img/topicThumbnails/javascript.svg
  img/topicThumbnails/ml.svg
  img/topicThumbnails/php.svg
  img/topicThumbnails/python.svg
  img/topicThumbnails/react.svg
  img/topicThumbnails/ruby.svg
  img/topicThumbnails/typescript.svg
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
Labels: awaiting review

#870 feat: add pagination to user insights page
  components/molecules/Pagination/pagination.tsx
  lib/hooks/useUserInsights.ts
  pages/[filterName]/insights/index.tsx
Labels: requested changes, api-updates-needed

#1015 feat: connect pull requests to API
  components/molecules/LatestPrTableRow/latest-pr-table-row.tsx
  components/molecules/PullRequestTable/pull-request-table.tsx
  next-types.d.ts
Labels: api-updates-needed

#1027 fix: center text inside upgrade access button
  components/organisms/StripeCheckoutButton/stripe-checkout-button.tsx
Labels: needs-approval

#1026 fix: make delete standout
  components/organisms/InsightPage/DeleteInsightPageModal.tsx
Labels: awaiting review

#1009 refactor: add a check for proper URL in avatarURL prop
  components/atoms/Avatar/avatar.tsx
Labels: ready-to-merge

#1029 feat: Responsive nav
  components/molecules/AuthSection/auth-section.tsx
  components/molecules/HeaderLogo/header-logo.tsx
  components/organisms/TopNav/top-nav.tsx
Labels: awaiting review

#1034 fix: update and delete highlight refresh
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  pages/feed/index.tsx
Labels: awaiting review

#1037 fix: update avatar style to remain aligned with the input field
  pages/feed/index.tsx
Labels: ready-to-merge

#999 fix: close dialogs when clicking outside
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/organisms/InsightPage/DeleteInsightPageModal.tsx
  components/organisms/InsightPage/InsightPage.tsx
  pages/feed/index.tsx
Labels: ready-to-merge, needs-approval

#1040 fix: updated footer.tsx file to update the year dynamically
  components/organisms/Footer/footer.tsx
  package.json
Labels: awaiting review

#933 feat: replace react toast to radix
  components/atoms/Toast/toast.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/molecules/Toaster/toaster.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  img/icons/error.svg
  img/icons/info.svg
  img/icons/success.svg
  lib/hooks/useToast.ts
  lib/utils/toast-trigger.ts
  npm-shrinkwrap.json
  package.json
  pages/_app.tsx
  pages/start.tsx
Labels: ready-to-merge

#1047 fix: dialog layout overlap on single highlight view
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/Dialog/dialog.tsx
  pages/feed/index.tsx
Labels: awaiting review, needs-approval

#1046 fix: insights hub layout inconsistencies on larger screens
  layouts/hub-page.tsx
  layouts/hub.tsx
Labels: awaiting review, needs-approval

#1042 feat: connect repositories to API
  components/molecules/InsightHeader/insight-header.tsx
  components/molecules/InsightPageCard/insight-page-card.tsx
  components/molecules/InsightRow/insight-row.tsx
  components/molecules/InsightTableRow/insight-table-row.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/molecules/TableRepositoryName/table-repository-name.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/RepositoriesTable/repositories-table.tsx
  lib/hooks/api/useRepositories.ts
  lib/hooks/useFilterPrefetch.ts
  lib/hooks/useLoginRepoList.ts
  lib/hooks/useNav.ts
  lib/hooks/useRepositoriesList.ts
  lib/utils/get-repo-insights.ts
  next-types.d.ts
  pages/hub/insights/[insightId]/edit.tsx
  pages/hub/insights/index.tsx
  pages/hub/insights/new.tsx
  stories/molecules/repositories-table.stories.tsx
  stories/molecules/table-repository-name.stories.tsx
Labels: ready-to-merge

#1045 feat: Repo recommendations UI
  components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
  stories/mockedData.tsx
  stories/molecules/insight-page-card.stories.tsx
  stories/molecules/recommended-repo-card.stories.tsx
  stories/molecules/stacked-avatar.stories.tsx
Labels: awaiting review

#1050 feat: add recommendation repo links
  lib/utils/recommendations.ts
Labels: requested changes

#1030 feat: add `ProfileLanguageChart` component to design system and user profile page
  components/molecules/CardHorizontalBarChart/card-horizontal-bar-chart.tsx
  components/molecules/ProfileLanguageChart/profile-language-chart.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  stories/molecules/card-horizontal-bar.stories.tsx
  stories/molecules/profile-language-chart.stories.tsx
Labels: ready-to-merge

#1062 v1.38.0-beta.8 -> production
  CHANGELOG.md
  components/atoms/Spinner/spinner.tsx
  components/molecules/CardHorizontalBarChart/card-horizontal-bar-chart.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/InsightHeader/insight-header.tsx
  components/molecules/InsightPageCard/insight-page-card.tsx
  components/molecules/InsightRow/insight-row.tsx
  components/molecules/InsightTableRow/insight-table-row.tsx
  components/molecules/ProfileLanguageChart/profile-language-chart.tsx
  components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/molecules/TableRepositoryName/table-repository-name.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/RepositoriesTable/repositories-table.tsx
  components/organisms/TopNav/top-nav.tsx
  layouts/hub-page.tsx
  lib/hooks/api/useRepositories.ts
  lib/hooks/useFilterPrefetch.ts
  lib/hooks/useLoginRepoList.ts
  lib/hooks/useNav.ts
  lib/hooks/useRepositoriesList.ts
  lib/utils/get-repo-insights.ts
  lib/utils/recommendations.ts
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/feed/index.tsx
  pages/hub/insights/[insightId]/edit.tsx
  pages/hub/insights/index.tsx
  pages/hub/insights/new.tsx
  pages/pages/[userOrg]/[filterName]/[toolName].tsx
  pages/pages/[userOrg]/[filterName]/[toolName]/filter/[...selectedFilter].tsx
  stories/atoms/spinner.stories.tsx
  stories/mockedData.tsx
  stories/molecules/card-horizontal-bar.stories.tsx
  stories/molecules/insight-page-card.stories.tsx
  stories/molecules/profile-language-chart.stories.tsx
  stories/molecules/recommended-repo-card.stories.tsx
  stories/molecules/repositories-table.stories.tsx
  stories/molecules/stacked-avatar.stories.tsx
  stories/molecules/table-repository-name.stories.tsx
Labels: api-updates-needed
