Repository open-sauced/app, pull requests merged in 2023-04, with the labels that each got.

#1069 feat: implement `follow` and `unfollow` feature
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  lib/hooks/useFollowUser.ts
  next-types.d.ts
  pages/user/[username]/index.tsx
  pages/user/settings.tsx
Labels: ready-to-merge

#1085 feat: implement highlight reaction features
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/useFetchAllEmojis.ts
  lib/hooks/useFollowUser.ts
  lib/hooks/useHighlightReactions.tsx
  lib/hooks/useUserHighlightReactions.ts
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/feed/index.tsx
Labels: needs-approval

#1094 v1.41.0-beta.2 -> production
  CHANGELOG.md
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  components/organisms/RepositoriesTable/repositories-table.tsx
  lib/hooks/useFetchAllEmojis.ts
  lib/hooks/useFilterPrefetch.ts
  lib/hooks/useFollowUser.ts
  lib/hooks/useHighlightReactions.tsx
  lib/hooks/useUserHighlightReactions.ts
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/feed/index.tsx
Labels: api-updates-needed

#1096 feat: redirect user to the dashboard with repos after onboarding
  pages/start.tsx
Labels: needs-approval

#1080 feat: implement insights team feature
  components/atoms/Search/search.tsx
  components/atoms/Selector/selector.tsx
  components/molecules/FilterCardSelect/filter-card-select.tsx
  components/molecules/TeamMemberRow/team-member-row.tsx
  components/molecules/TeamMembersConfig/team-members-config.tsx
  components/organisms/InsightPage/InsightPage.tsx
  lib/hooks/useInsightMembers.ts
  next-types.d.ts
  pages/hub/insights/[insightId]/edit.tsx
  stories/atoms/selector.stories.tsx
  stories/atoms/team-member-row.stories.tsx
  stories/atoms/team-members-config.stories.tsx
Labels: ready-to-merge

#1089 fix: adds spacing to contributor highlights container
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: requested changes, merge conflicts

#1122 feat: connect dashboard insights to API
  components/organisms/Dashboard/dashboard.tsx
  lib/hooks/api/useContributors.ts
  lib/hooks/api/useInsights.ts
  lib/hooks/api/usePullRequests.ts
  lib/hooks/api/useRepositories.ts
Labels: api-updates-needed

#1126 feat: adds a share button to profile
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: awaiting review, ready-to-merge

#1117 fix: connect reports to the API
  components/molecules/ReportsHistory/csv-download.tsx
  components/molecules/ReportsHistory/reports-history.tsx
  components/molecules/SelectReportsFilter/select-reports-filter.tsx
  lib/utils/get-current-date.ts
Labels: ready-to-merge

#1107 refactor: Improve select structure for accessibility and reusability
  components/atoms/Radio/radio.tsx
  components/atoms/Select/custom-select.tsx
  components/atoms/Select/limit-select.tsx
  components/atoms/Select/select-option.tsx
  components/atoms/Select/select.tsx
  components/atoms/Selector/selector.tsx
  components/molecules/FilterCardSelect/filter-card-select.tsx
  components/molecules/SelectReportsFilter/select-reports-filter.tsx
  components/molecules/TableHeader/table-header.tsx
  components/molecules/TeamMemberRow/team-member-row.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  lib/utils/timezones.ts
  npm-shrinkwrap.json
  package.json
  pages/start.tsx
  stories/atoms/custom-select.stories.tsx
  stories/atoms/limit-select.stories.tsx
  stories/atoms/select.stories.tsx
  stories/atoms/selector.stories.tsx
Labels: awaiting review, needs-approval
