Repository open-sauced/app, pull requests merged in 2023-01, with the labels that each got.

#693 feat: repository selection & add to insights
  components/atoms/Checkbox/checkbox.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/molecules/TableRepositoryName/table-repository-name.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/RepositoriesTable/repositories-table.tsx
Labels: requested changes

#738 feat: add Edit Page button to insight pages
  components/molecules/InsightHeader/insight-header.tsx
  layouts/hub-page.tsx
  lib/hooks/useSupabaseAuth.ts
Labels: requested changes

#705 feat: handle close modal when click outside and fix accessibility issues
  components/atoms/Select/custom-select.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/Repositories/repositories.tsx
  npm-shrinkwrap.json
  package.json
  stories/atoms/custom-select.stories.tsx
  tailwind.config.js
Labels: awaiting review

#742 feat: add hover card and expand on contributor stack
  components/atoms/Avatar/avatar-hover-card.tsx
  components/molecules/CardProfile/card-profile.tsx
  components/molecules/HighlightCard/highlight-card.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/molecules/StackedAvatar/stacked-avatar.tsx
  npm-shrinkwrap.json
  package.json
  stories/atoms/avatar-hover-card.stories.tsx
Labels: requested changes

#706 feat: update icon PR details row
  components/molecules/CardRepoList/card-repo-list.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  next-types.d.ts
  pages/user/[username].tsx
  stories/molecules/insight-page-card.stories.tsx
Labels: requested changes

#735 feat: add public/private insights badge
  components/atoms/InsightBadge/insight-badge.tsx
  components/molecules/InsightHeader/insight-header.tsx
  stories/atoms/insight-badge.stories.tsx
Labels: requested changes

#771 feat: add custom profile banner for verified OpenSauced user
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  img/rainbow-cover.png
  lib/hooks/useFetchUser.ts
  next-types.d.ts
  pages/user/[username].tsx
  stories/molecules/contributor-profile-header.stories.tsx
  stories/molecules/insight-page-card.stories.tsx
Labels: awaiting review

#788 feat: add `UserSettings` component to design system
  components/atoms/Button/button.tsx
  components/atoms/Checkbox/checkbox.tsx
  components/atoms/LanguagePill/LanguagePill.tsx
  components/atoms/Pill/pill.tsx
  components/atoms/TextInput/text-input.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  img/icons/☕️.svg
  img/icons/⚛️.svg
  img/icons/🐍.svg
  img/icons/🤖.svg
  img/icons/🦀.svg
  img/icons/🧠.svg
  npm-shrinkwrap.json
  package.json
  stories/atoms/language-pill.stories.tsx
  stories/organisms/user-settings-page.stories.tsx
  styles/globals.css
Labels: awaiting review

#813 feat: set insight repo limit based on role
  components/organisms/InsightPage/InsightPage.tsx
  interfaces/global-state-types.ts
  lib/hooks/useSession.ts
  lib/store/index.ts
Labels: api-updates-needed
