Repository open-sauced/app, pull requests merged in 2023-06, with the labels that each got.

#1208 fix: redirect user to dashboard after logout on private pages
  components/organisms/Reports/reports.tsx
  e2e-tests/UnsignedUsersRedirects.spec.ts
  interfaces/with-page-layout.ts
  layouts/private-wrapper.tsx
  middleware.ts
  pages/_app.tsx
  pages/hub/insights/[insightId]/accept.tsx
  pages/hub/insights/[insightId]/edit.tsx
  pages/hub/insights/index.tsx
  pages/hub/insights/new.tsx
  pages/pages/[userOrg]/[filterName]/[toolName].tsx
  pages/user/settings.tsx
Labels: needs-approval

#1236 fix: force login in reports page
  components/organisms/Reports/reports.tsx
Labels: ready-to-merge

#1239 fix: reports select issue
  components/molecules/SelectReportsFilter/select-reports-filter.tsx
  stories/molecules/select-reports-filter.stories.tsx
Labels: awaiting review

#1240 feat: implement dynamic redirect on auth
  components/molecules/AuthSection/auth-section.tsx
  lib/hooks/useSupabaseAuth.ts
Labels: awaiting review

#1221 feat: implement user collaboration features
  components/atoms/Textarea/text-area.tsx
  components/molecules/CollaborationCard/collaboration-card.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/organisms/CollaborationRequestWrapper/collaboration-requests-wrapper.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/useUserCollaborations.ts
  next-types.d.ts
  stories/molecules/collaboration-card.stories.tsx
  stories/molecules/collaboration-summary-card.stories.tsx
Labels: needs-approval

#1258 feat: add openGraph image to public insight pages
  components/molecules/InsightHeader/insight-header.tsx
  lib/utils/fetch-social-card.ts
  pages/feed/[id].tsx
  pages/feed/index.tsx
  pages/pages/[userOrg]/[filterName]/[toolName].tsx
  pages/user/[username]/index.tsx
Labels: ready-to-merge

#1268 feat: handle close highlight dialog
  pages/feed/index.tsx
Labels: ready-to-merge

#1266 fix: scatter plot tooltip issue and remove cloudinary rounded image solution
  components/atoms/Avatar/avatar-hover-card.tsx
  components/molecules/CardProfile/card-profile.tsx
  components/molecules/ContributorHoverCard/contributor-hover-card.tsx
  components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
  components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
  components/organisms/Dashboard/dashboard.tsx
  lib/utils/roundedImages.ts
Labels: ready-to-merge

#1279 fix: linked single highlight dialog's contributor info div to contributor profile
  pages/feed/index.tsx
Labels: awaiting review

#1278 feat: Devcard Carousel
  components/atoms/Button/button.tsx
  components/molecules/DevCard/dev-card.tsx
  components/organisms/DevCardCarousel/dev-card-carousel.test.tsx
  components/organisms/DevCardCarousel/dev-card-carousel.tsx
  components/organisms/DevCardCarousel/stubData.ts
  img/bubble-bg.svg
  npm-shrinkwrap.json
  package.json
  pages/user/[username]/card.tsx
  stories/atoms/button.stories.tsx
  stories/organisms/dev-card-carousel.stories.tsx
Labels: requested changes

#1282 fix: properly format local time displayed on user's profile
  lib/utils/timezones.ts
Labels: awaiting review

#1184 feat: force login (close #1132)
  components/molecules/AuthSection/auth-section.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/Repositories/repositories.tsx
  layouts/private-wrapper.tsx
  lib/hooks/useSupabaseAuth.ts
  lib/store/index.ts
  middleware.ts
Labels: requested changes

#1300 feat: add top users panel component to design system
  components/atoms/TopUserCard/top-user-card.tsx
  components/molecules/TopUsersPanel/top-user-panel.tsx
  stories/atoms/top-user-card.stories.tsx
  stories/molecules/top-users-panel.stories.tsx
Labels: awaiting review

#1304 feat: hide highlights tab components on profiles without highlights
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: ready-to-merge

#1306 feat: add `BillBoard` component to design system
  components/molecules/Billboard/billboard.tsx
  npm-shrinkwrap.json
  package.json
  stories/molecules/bill-board.stories.tsx
Labels: awaiting review

#1322 fix: DevCard component first contribution date format
  components/molecules/DevCard/dev-card.tsx
Labels: needs-approval
