Repository open-sauced/app, pull requests merged in 2023-02, with the labels that each got.

#808 feat: implement profile settings feature
  components/atoms/Avatar/avatar.tsx
  components/atoms/Checkbox/checkbox.tsx
  components/atoms/TextInput/text-input.tsx
  components/molecules/AuthSection/auth-section.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  lib/hooks/authSession.ts
  lib/hooks/update-user.ts
  lib/hooks/updateEmailPreference.ts
  lib/hooks/useFetchUser.ts
  lib/utils/timezones.ts
  lib/utils/toast-trigger.ts
  lib/utils/validate-email.ts
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/_app.tsx
  pages/user/settings.tsx
  stories/organisms/user-settings-page.stories.tsx
Labels: awaiting review

#824 feat: add profile badge to connected user profile
  components/atoms/Badge/badge.tsx
  components/atoms/InsightBadge/insight-badge.tsx
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  layouts/profile.tsx
  stories/atoms/badge.stories.tsx
  stories/atoms/insight-badge.stories.tsx
Labels: awaiting review

#834 feat: adds loading skeleton to page
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
Labels: ready-to-merge

#836 feat: add highlights input form to design system
  components/molecules/HighlightInput/highlight-input-form.tsx
  stories/molecules/highlight-input.stories.tsx
Labels: awaiting review

#848 refactor: use github avatar link instead of cached one
  components/molecules/TableRepositoryName/table-repository-name.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
Labels: awaiting review

#861 feat: add support for repo full name for onboarding/insight repos
  components/organisms/InsightPage/InsightPage.tsx
  next-types.d.ts
  pages/start.tsx
Labels: api-updates-needed

#869 fix: reset text input fields when clear button is clicked
  components/atoms/TextInput/text-input.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  pages/start.tsx
Labels: awaiting review
