Repository open-sauced/app, pull requests merged in 2023-11, with the labels that each got.

#2029 fix: chart tooltip cut in contributors card
  components/organisms/ContributorCard/contributor-card.tsx
Labels: awaiting review

#2040 fix: dropdown flickery on single highlight card
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  stories/atoms/toggle-switch.stories.tsx
Labels: awaiting review

#2058 fix: styling tweaks to header areas and box shadow tweaks
  components/TabList/tab-list.tsx
  components/atoms/Card/card.tsx
  components/atoms/Dropdown/dropdown.tsx
  components/atoms/LayoutToggle/layout-toggle.tsx
  components/atoms/Select/select.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/molecules/PieChart/pie-chart.tsx
  components/molecules/Popover/popover.tsx
  components/organisms/Header/header.tsx
  components/organisms/ToolList/nav.tsx
  components/organisms/TopNav/top-nav.tsx
  layouts/filter.tsx
  layouts/hub-contributors.tsx
  layouts/hub-page.tsx
  layouts/lists.tsx
  tailwind.config.js
Labels: awaiting review

#2075 fix: removed unnecessary CTAs for creating new lists/insights
  pages/hub/insights/index.tsx
  pages/hub/lists/index.tsx
Labels: needs-second-review

#2038 fix: add accessibility features to footer component
  components/organisms/Footer/footer.tsx
Labels: requested changes

#2050 fix: Fix Accessibility issues in user's settings page - `user/settings`
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: awaiting review

#2080 fix: top contributor is now updated with filters in list graph
  components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
  pages/lists/[listId]/activity.tsx
Labels: awaiting review

#2068 feat: show most recent contributions for contributors instead of last 30 days
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
  components/molecules/PullRequestTable/pull-request-table.tsx
  components/organisms/ContributorCard/contributor-card.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  lib/hooks/api/useContributorPullRequests.ts
  lib/hooks/useContributorPullRequestsChart.ts
  lib/utils/get-prs-to-days.ts
  pages/user/[username]/index.tsx
Labels: api-updates-needed, needs-second-review

#2026 feat: add nprogress bar for page transition indication
  npm-shrinkwrap.json
  package.json
  pages/_app.tsx
Labels: awaiting review, needs-approval

#1762 feat: select component growth enabled
  components/atoms/Select/select.tsx
  components/molecules/ComponentDateFilter/component-date-filter.tsx
  styles/globals.css
Labels: awaiting review, needs-approval

#2047 feat: move range filter to global header
  components/molecules/ComponentDateFilter/component-date-filter.tsx
  components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
  components/molecules/InsightHeader/insight-header.tsx
  components/molecules/PullRequestTable/pull-request-table.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/ContributorCard/contributor-card.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/ToolList/nav-item.tsx
  components/organisms/ToolList/nav.tsx
  layouts/filter.tsx
  layouts/hub-page.tsx
  layouts/lists.tsx
  lib/hooks/api/useContributionsByProject.ts
  lib/hooks/api/useContributorList.ts
  lib/hooks/api/useContributorPullRequests.ts
  lib/hooks/api/useContributors.ts
  lib/hooks/api/useContributorsByProject.ts
  lib/hooks/api/useMostActiveContributors.ts
  lib/hooks/api/useRepositories.ts
  lib/hooks/useContributorPullRequestsChart.ts
  lib/hooks/useNav.ts
  lib/store/index.ts
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/contributors.tsx
  pages/lists/[listId]/overview.tsx
  pages/user/[username]/index.tsx
Labels: awaiting review, needs-approval

#2106 fix: fixed styling of delete list modal
  pages/hub/lists/index.tsx
Labels: awaiting review

#2119 fix: insights edit repo list limit
  components/organisms/RepositoriesCart/repositories-cart.tsx
  lib/hooks/api/useRepositories.ts
  pages/hub/insights/[insightId]/edit.tsx
Labels: awaiting review

#2101 feat: implemented the Contributions by type of contributor graph for the list activity page
  components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx
  lib/hooks/api/useContributionsByEvolutionType.ts
  pages/lists/[listId]/activity.tsx
  stories/molecules/contributions-evolution-by-type.stories.tsx
Labels: merge conflicts

#2113 refactor: Replace hardcoded px value with appropriate tailwind class in Dropdown component
  components/atoms/Dropdown/dropdown.tsx
Labels: awaiting review

#2125 fix: added Edit List button to all list pages
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/contributors.tsx
Labels: ready-to-merge

#2112 fix: Remove the unused components - `CommandEmpty` and `CommandLis`t from the codebase
  components/atoms/Cmd/command.tsx
Labels: awaiting review

#2130 feat: replace dashboard scatterplot chart with repositories table
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Activity/activity.tsx
  components/organisms/Dashboard/dashboard.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/ToolsDisplay/tools-display.tsx
  lib/hooks/useNav.ts
  pages/[pageId]/[toolName].tsx
  pages/pages/[userOrg]/[pageId]/[toolName].tsx
Labels: awaiting review

#2152 fix: hover card now works as expected in all areas
  components/atoms/Avatar/avatar-hover-card.tsx
Labels: awaiting review

#2142 fix: h1-h6 base style using CSS from .tracking-tight
  components/ListHeader/list-header.tsx
  components/molecules/FilterHeader/filter-header.tsx
  components/molecules/InsightHeader/insight-header.tsx
  components/molecules/OnboardingButton/onboarding-button.tsx
  components/molecules/PageHeader/page-header.tsx
  components/organisms/Waitlist/waitlist.tsx
  pages/start.tsx
  styles/globals.css
Labels: needs-second-review

#2062 feat: add params handling for new PR
  components/molecules/HighlightInput/highlight-input-form.tsx
  pages/feed/index.tsx
Labels: awaiting review, needs-response

#2146 fix: removed font-medium classes as the base style for all elements is font-medium
  components/atoms/Checkbox/checkbox.tsx
  components/atoms/Cmd/command.tsx
  components/atoms/Dropdown/dropdown.tsx
  components/atoms/Tabs/tabs.tsx
  components/atoms/Toast/toast.tsx
  components/molecules/Calendar/calendar.tsx
  components/molecules/ContributionsEvolution/contributions-evolution-card.tsx
  components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx
  components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
  components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
  components/molecules/TeamMembersConfig/team-members-config.tsx
  components/organisms/RepositoriesCart/repositories-cart.tsx
  components/organisms/TopNav/top-nav.tsx
  components/organisms/UserSettingsPage/coupon-form.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  layouts/hub.tsx
  pages/start.tsx
  stories/molecules/treemap-prototype/contributor-node.tsx
  stories/molecules/treemap-prototype/special-node.tsx
  styles/globals.css
Labels: needs-second-review

#2133 feat: add ability for user to toggle receiving email product updates
  components/organisms/UserSettingsPage/user-settings-page.tsx
  next-types.d.ts
Labels: api-updates-needed, needs-second-review

#2115 feat: updating last contributed column for insights table
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/DevProfile/dev-profile.tsx
  stories/molecules/contributor-list-table-row.stories.tsx
  stories/molecules/dev-profile.stories.tsx
Labels: needs-second-review

#2102 fix: refactor TableRepositoryName prop naming
  components/molecules/TableRepositoryName/table-repository-name.tsx
Labels: needs-second-review

#2159 fix: changed delete button color to match the ui
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: ready-to-merge

#2168 feat: Svelte added to interests dropdown list
  components/atoms/LanguagePill/LanguagePill.tsx
  img/topic-thumbnails/svelte.svg
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
  lib/utils/recommendations.ts
Labels: failed build

#2184 fix: reset base font size in * selector in global.css
  components/Graphs/MostUsedLanguagesGraph/most-used-languages-graph.tsx
  styles/globals.css
Labels: needs-second-review

#2196 fix: added missing svelte svg
  components/atoms/LanguagePill/LanguagePill.tsx
  img/icons/interests/svelte.svg
Labels: needs-second-review

#2153 refactor: move limit query from state to urlParams
  components/atoms/Select/limit-select.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  components/organisms/Repositories/repositories.tsx
  lib/hooks/api/useContributorList.ts
  lib/hooks/api/useRepositories.ts
  lib/hooks/useFetchAllContributors.ts
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/contributors.tsx
Labels: awaiting review

#2088 refactor: fix tailwind anti-pattern in feed footer
  components/organisms/Footer/footer.tsx
  components/organisms/SearchDialog/search-dialog.tsx
  pages/feed/index.tsx
  pages/user/notifications.tsx
Labels: needs-response

#2212 fix: made checkbox stroke thicker
  components/atoms/Checkbox/checkbox.tsx
  styles/globals.css
Labels: ready-to-merge

#2192 fix: improved type inference of interests and recommendations
  components/atoms/LanguagePill/LanguagePill.tsx
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/molecules/FilterHeader/filter-header.tsx
  components/organisms/UserRepositoryRecommendations/user-repository-recommendations.tsx
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
  lib/utils/recommendations.ts
Labels: ready-to-merge

#2224 fix: cleaned up list activity graph title styling
  components/Graphs/MostUsedLanguagesGraph/most-used-languages-graph.tsx
  components/molecules/ContributionsEvolution/contributions-evolution-card.tsx
  components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx
  components/molecules/ContributionsTreemap/contributions-treemap.tsx
  components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
Labels: needs-second-review

#2214 fix: list activity and contirbutor page rerender issue
  components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  lib/hooks/api/useContributionsByEvolutionType.ts
  lib/hooks/api/useContributionsByProject.ts
  lib/hooks/api/useContributorsByProject.ts
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/contributors.tsx
Labels: awaiting review, needs-second-review
