Repository open-sauced/app, pull requests merged in 2023-08, with the labels that each got.

#1460 fix: hide onboarding button on mobile
  components/molecules/OnboardingButton/onboarding-button.tsx
Labels: awaiting review

#1458 chore: add links to user profile on feeds userCard
  components/atoms/UserCard/user-card.tsx
Labels: awaiting review

#1464 feat: update redirect to feed page for unauthenticated users
  e2e-tests/UnsignedUsersRedirects.spec.ts
  middleware.ts
  pages/hub/insights/index.tsx
  pages/index.tsx
Labels: needs-approval

#1466 fix: add checkbox id name if not available based on label
  components/atoms/Checkbox/checkbox.tsx
Labels: awaiting review

#1474 fix: user interest logo error
  components/atoms/LanguagePill/LanguagePill.tsx
Labels: awaiting review

#1473 feat: add conditional routing to single highlight dialog close action
  pages/feed/[id].tsx
  pages/feed/index.tsx
Labels: awaiting review

#1467 fix: feeds page typography and styles improvements
  components/atoms/TopContributorCard/top-contributor-card.tsx
  components/atoms/UserCard/user-card.tsx
  components/molecules/AnnouncementCard/announcement-card.tsx
  components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  components/molecules/TopContributorsPanel/top-contributors-panel.tsx
Labels: awaiting review

#1438 refactor: replace supabase/ui in design system typography components
  components/atoms/Typography/text.tsx
  components/atoms/Typography/title.tsx
  components/atoms/Typography/wrapper.tsx
  npm-shrinkwrap.json
  package.json
  stories/atoms/text.stories.tsx
  stories/atoms/title.stories.tsx
  stories/atoms/typography-wrapper.stories.tsx
  tailwind.config.js
Labels: awaiting review

#1490 fix: Feed page responsiveness
  components/atoms/UserCard/user-card.tsx
  layouts/profile.tsx
  pages/feed/index.tsx
Labels: awaiting review

#1488 feat: onboarding auto fetch timezone
  pages/start.tsx
Labels: ready-to-merge

#1500 feat: add repositories cart title
  components/organisms/RepositoriesCart/repositories-cart.tsx
Labels: requested changes

#1536 fix: disabled the button while it's loading, so it doesn't add the same repo again
  components/molecules/SuggestedRepo/suggested-repo.tsx
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/SuggestedRepoList/suggested-repo-list.tsx
Labels: awaiting review

#1492 fix: add space between avatar and cta menu
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: awaiting review

#1537 fix: refactor notification username retrieval and display logic
  lib/utils/get-notification-url.ts
  next-types.d.ts
  pages/user/notifications.tsx
Labels: awaiting review

#1470 feat: Support full URLs when adding repo to insights page
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/organisms/InsightPage/InsightPage.tsx
  lib/utils/github.ts
  tests/lib/utils/github.test.ts
Labels: awaiting review

#1570 fix: add bg color to reports select filter
  components/molecules/SelectReportsFilter/select-reports-filter.tsx
Labels: needs-approval

#1577 fix: corrected repo card for mobile
  components/molecules/SuggestedRepo/suggested-repo.tsx
Labels: awaiting review

#1584 fix: highlights nav item unselected when there were query params in URL
  components/organisms/TopNav/top-nav.tsx
Labels: ready-to-merge

#1590 fix: overflows in insights page on md screen size
  layouts/hub.tsx
Labels: awaiting review

#1595 fix: Highlights in user profile page breaks when a repo is tagged
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: awaiting review

#1596 fix: issue-#1418 refetch following count after following a user
  components/atoms/TopContributorCard/top-contributor-card.tsx
  components/molecules/TopContributorsPanel/top-contributors-panel.tsx
  pages/feed/index.tsx
Labels: requested changes

#1597 fix: query param reset in repo filters & URL encoding
  components/organisms/FollowersHighlightWrapper/following-highlight-wrapper.tsx
  lib/utils/query-params.ts
  pages/feed/index.tsx
Labels: awaiting review

#1588 feat: "Following" button to "Unfollow" on hover
  components/atoms/TopContributorCard/top-contributor-card.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: needs-approval

#1607 refactor: update top users implementation to remove already followed users
  components/molecules/TopContributorsPanel/top-contributors-panel.tsx
  lib/hooks/useFetchTopContributors.ts
  pages/feed/index.tsx
Labels: ready-to-merge

#1591 feat: show reactors who reacted to highlights
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  lib/hooks/useHighlightReactions.ts
Labels: awaiting review

#1623 fix: hidden link on profile highlights (1618)
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: awaiting review

#1621 fix: add support for blog highlight update
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  lib/hooks/updateHighlight.ts
Labels: awaiting review

#1617 fix: repo filter query not filtering on page refresh (1610)
  components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
  pages/feed/index.tsx
  stories/molecules/highlights-filter-card.stories.tsx
Labels: awaiting review

#1613 feat: profile tabs - path params to query params (1229)
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  e2e-tests/CloseSingleHighlight.spec.ts
  next.config.js
  pages/user/[username]/contributions.tsx
  pages/user/[username]/highlights.tsx
  pages/user/[username]/recommendations.tsx
  pages/user/[username]/requests.tsx
Labels: awaiting review

#1635 fix: lint check happening two times on commit
  .husky/pre-commit
Labels: awaiting review

#1633 refactor: calcDistanceFromToday function
  lib/utils/date-utils.ts
Labels: awaiting review

#1637 fix: remove tailwind anti-pattern from the repo
  .husky/pre-commit
  components/atoms/CartIllustration/cart-illustration.tsx
  pages/feed/index.tsx
Labels: awaiting review

#1631 fix: show highlights tab without highlights
  CHANGELOG.md
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  e2e-tests/OpenUserProfile.spec.ts
Labels: awaiting review
