Repository open-sauced/app, pull requests merged in 2023-12, with the labels that each got.

#2238 fix: now most used languages are truncated to a limit of two
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
Labels: awaiting review

#2284 fix: show contributor url on profile page
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
Labels: awaiting review

#2340 test: <SingleSelect /> Storybook story
  components/atoms/Select/single.select.stories.tsx
Labels: ready-to-merge

#2356 fix: now destructive variant is used for destructive actions in the app
  components/atoms/Button/button.tsx
  components/organisms/InsightPage/DeleteInsightPageModal.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  pages/hub/lists/index.tsx
Labels: awaiting review

#2061 feat: make single select component searchable
  components/atoms/Cmd/command.tsx
  components/atoms/Select/single-select.tsx
  components/atoms/Select/single.select.stories.tsx
  components/molecules/HubContributorsHeader/hub-contributors-header.tsx
Labels: requested changes, needs-second-review

#2371 chore: remove hacktoberfest interest and topic from app
  components/atoms/ContextThumbnail/context-thumbnail.stories.tsx
  components/organisms/TopNav/top-nav.tsx
  lib/utils/getInterestOptions.ts
Labels: awaiting review, needs-response

#2378 fix: quick fix for build error introduced in #2371
  components/shared/LanguagePill/LanguagePill.tsx
  lib/utils/getTopicThumbnail.ts
  lib/utils/recommendations.ts
Labels: awaiting review

#2344 feat: use GitHub API to search for contributors to add to a list
  components/AddContributorsHeader/add-contributors-header.tsx
  components/atoms/Search/search.tsx
  components/molecules/HubContributorsHeader/hub-contributors-header.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  lib/hooks/search-users.ts
  pages/hub/lists/find.tsx
  pages/lists/[listId]/add-contributors.tsx
Labels: awaiting review

#2361 fix: broken pagination
  components/molecules/Pagination/pagination.tsx
Labels: requested changes

#2309 chore: add helper tooltip to dashboard highlight cards
  components/molecules/HighlightCard/highlight-card.tsx
  components/organisms/Dashboard/dashboard.tsx
Labels: needs-second-review

#2377 docs: add sidebar component prototype to storybook
  components/Sidebar/sidebar-group-wrapper.stories.tsx
  components/Sidebar/sidebar-group-wrapper.tsx
  components/Sidebar/sidebar-menu-header.stories.tsx
  components/Sidebar/sidebar-menu-header.tsx
  components/Sidebar/sidebar-menu-item.stories.tsx
  components/Sidebar/sidebar-menu-item.tsx
  components/Sidebar/sidebar-wrapper.stories.tsx
  components/Sidebar/sidebar-wrapper.tsx
Labels: ready-to-merge

#2227 fix: now page limit dropdown filters works on repo table
  components/ListHeader/list-header.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  components/organisms/Dashboard/dashboard.tsx
  components/organisms/Repositories/repositories.tsx
  layouts/hub-page.tsx
  lib/hooks/api/useContributors.ts
Labels: awaiting review

#2385 feat: replace contribution distribution chart with contributors table in list overview page
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  layouts/lists.tsx
  next.config.js
  pages/lists/[listId]/contributors.tsx
  pages/lists/[listId]/overview.tsx
Labels: needs-second-review
