Repository open-sauced/app, pull requests merged in 2023-05, with the labels that each got.

#1129 fix: user-setting-page breaks in ipad-mini
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: ready-to-merge

#1127 fix: toast inaccessible menu (#1098)
  components/atoms/Toast/toast.tsx
Labels: ready-to-merge

#1121 feat: replace supabase checkbox with radix ui
  components/atoms/Checkbox/checkbox.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/organisms/Repositories/repositories.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  stories/atoms/checkbox.stories.tsx
Labels: ready-to-merge

#1116 feat: highlight date selection
  components/atoms/Tooltip/tooltip.tsx
  components/molecules/Calendar/calendar.tsx
  components/molecules/Collapsible/collapsible.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/molecules/Popover/popover.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/createHighlights.ts
  lib/hooks/updateHighlight.ts
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/feed/index.tsx
  stories/molecules/calendar.stories.tsx
  stories/molecules/highlight-input.stories.tsx
Labels: awaiting review

#1136 feat: add notification card to design system
  components/atoms/NotificationsCard/notification-card.tsx
  components/molecules/AuthSection/auth-section.tsx
  stories/atoms/notification-card.stories.tsx
  tailwind.config.js
Labels: needs-approval

#1137 fix: auto row expansion on text area
  components/atoms/Textarea/text-area.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: awaiting review

#1170 feat: add context clue card to design system
  components/molecules/ContextClueCard/context-clue-card.tsx
  stories/molecules/context-clue-card.stories.tsx
Labels: awaiting review

#1174 feat: add repo recommendations to user profile
  components/atoms/DashedContainer/DashContainer.tsx
  components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/api/useRepositoryPullRequests.ts
  lib/hooks/fetchRecommendationByRepo.ts
  next-types.d.ts
  stories/molecules/recommended-repo-card.stories.tsx
Labels: awaiting review

#1186 feat: implement followers highlights tab
  components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
  components/organisms/FollowersHighlightWrapper/following-highlight-wrapper.tsx
  components/organisms/HomeHighlightsWrapper/home-highlights-wrapper.tsx
  lib/hooks/useFetchFollowingHighlightRepos.ts
  lib/hooks/useFetchFollowingHighlights.ts
  pages/feed/index.tsx
  stories/molecules/highlights-filter-card.stories.tsx
Labels: ready-to-merge

#1214 fix: set default value to repo filter state
  pages/feed/index.tsx
Labels: awaiting review

#1218 feat: hide chatbot on non-prod environment and mobile screens
  pages/_app.tsx
Labels: ready-to-merge

#1228 fix: format highlight date on feeds page to distance from now
  components/organisms/FollowersHighlightWrapper/following-highlight-wrapper.tsx
  components/organisms/HomeHighlightsWrapper/home-highlights-wrapper.tsx
Labels: awaiting review

#1195 fix: pagination medium screens
  components/molecules/Pagination/pagination.tsx
  components/molecules/PaginationGotoPage/pagination-goto-page.tsx
  components/molecules/PaginationResults/pagination-result.tsx
  pages/feed/index.tsx
Labels: awaiting review

#1211 feat: implement contributor list view
  components/atoms/LayoutToggle/layout-toggle.tsx
  components/atoms/TableTitle/table-title.tsx
  components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/DevProfile/dev-profile.tsx
  components/molecules/InsightPageTable/insight-page-table.tsx
  components/molecules/RepoRow/repo-row.tsx
  components/molecules/ReportsHistory/reports-history.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  components/organisms/Repositories/repositories.tsx
  lib/hooks/useHighlightReactions.ts
  next-types.d.ts
  stories/atoms/table-title.stories.tsx
Labels: awaiting review

#1232 fix: search result suggestions click non-responsiveness
  components/atoms/Search/search.tsx
Labels: awaiting review
