Repository open-sauced/app, pull requests merged in 2023-10, with the labels that each got.

#1772 fix: made card view for lists contributors list uniform with rest of app
  components/organisms/ContributorsList/contributors-list.tsx
  pages/lists/[listId]/contributors.tsx
Labels: 🎨 style

#1775 feat: added hacktoberfest icon in user settings
  components/atoms/LanguagePill/LanguagePill.tsx
  img/icons/interests/hacktoberfest.svg
Labels: awaiting review

#1771 feat: add form to user settings to apply coupon code
  components/organisms/UserSettingsPage/coupon-form.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  next-types.d.ts
Labels: awaiting review

#1789 fix: Improve the input's width to accommodate full URL
  components/atoms/Search/search.tsx
Labels: requested changes

#1809 fix: hide weird top nav for edit insight page
  layouts/hub.tsx
Labels: awaiting review

#1808 refactor: redirect user to newly created insight page after creation
  components/atoms/Button/button.tsx
  components/organisms/InsightPage/InsightPage.tsx
Labels: awaiting review

#1819 fix: now range filter works on list contributors page grid view
  components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  lib/hooks/api/useContributorList.ts
  pages/lists/[listId]/contributors.tsx
Labels: awaiting review

#1811 fix: Fix re-rendering of Highlights "Repositories" table with duplicates
  components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
  pages/feed/index.tsx
Labels: awaiting review

#1798 feat: add new lists creation page
  components/atoms/Toast/toast.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/DevProfile/dev-profile.tsx
  components/molecules/InfoCard/info-card.tsx
  components/molecules/ListCard/list-card.tsx
  components/organisms/ContributorsList/contributors-list.tsx
  components/organisms/GitHubImportDialog/github-import-dialog.tsx
  lib/hooks/api/useContributorList.ts
  next-types.d.ts
  pages/hub/lists/find.tsx
  pages/hub/lists/new.tsx
Labels: awaiting review

#1831 refactor: update all collaboration copy to connection
  components/atoms/NotificationsCard/notification-card.tsx
  components/molecules/ConnectionCard/connection-card.tsx
  components/molecules/ConnectionSummaryCard/connection-summary-card.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/organisms/ConnectionRequestWrapper/connection-requests-wrapper.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  lib/hooks/useUserConnections.ts
  next-types.d.ts
  pages/feed/index.tsx
  stories/atoms/notification-card.stories.tsx
  stories/molecules/collaboration-card.stories.tsx
  stories/molecules/collaboration-summary-card.stories.tsx
Labels: needs-approval

#1769 fix: Repos with long names get cut off
  components/molecules/TableRepositoryName/table-repository-name.tsx
Labels: requested changes

#1857 feat: upgrade posthog version to support posthog survey feedback
  npm-shrinkwrap.json
  package.json
Labels: awaiting review

#1858 fix: show link to hub list page in nav
  layouts/hub.tsx
Labels: awaiting review

#1862 feat: add contributor search to list contributors
  components/molecules/HubContributorsHeader/hub-contributors-header.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  lib/hooks/useFetchAllContributors.ts
  pages/hub/lists/find.tsx
Labels: api-updates-needed

#1859 feat: display featured insight pages to new contributors
  components/molecules/InsightRow/insight-row.tsx
  interfaces/global-state-types.ts
  lib/store/index.ts
  next-types.d.ts
  pages/hub/insights/index.tsx
Labels: awaiting review

#1839 feat: add new "Get Card" CTA button to profile
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  img/icons/pizza-gradient.svg
  styles/globals.css
Labels: awaiting review

#1760 feat: Add OS detection hook and update search dialog
  components/organisms/SearchDialog/search-dialog.tsx
  lib/hooks/useIsMacOS.ts
Labels: requested changes

#1782 fix: adjust style for newsletter form so that it adjusts for smaller screens
  components/atoms/TextInput/text-input.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  styles/globals.css
Labels: awaiting review

#1881 fix: Unnecesary X-Scrollbar in tablist
  components/TabList/tab-list.tsx
Labels: ready-to-merge

#1897 fix: add target for the link
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
Labels: awaiting review

#1889 fix: attempt to clear any preset service workers
  pages/_app.tsx
Labels: ready-to-merge

#1803 feat: show onboarding btn on small screens
  .eslintrc.json
  components/molecules/AuthSection/auth-section.tsx
  components/molecules/OnboardingButton/onboarding-button.tsx
  components/organisms/TopNav/top-nav.tsx
Labels: awaiting review

#1901 feat: add clojure to dashboard interests
  components/atoms/LanguagePill/LanguagePill.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  img/icons/interests/clojure.svg
  img/topic-thumbnails/clojure.svg
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
  lib/utils/recommendations.ts
  npm-shrinkwrap.json
Labels: awaiting review

#1892 fix: add responsiveness to profile detail
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
Labels: ready-to-merge

#1825 fix: replace hash icon to arrow down for filter select
  components/molecules/FilterCardSelect/filter-card-select.tsx
Labels: ready-to-merge

#1925 fix: hide secondary header in create insights page
  layouts/hub.tsx
Labels: awaiting review

#1923 fix: decreased delay time of tooltips
  components/atoms/Tooltip/tooltip.tsx
  components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
Labels: awaiting review

#1930 fix: match graph tooltip color with graph nodes
  components/molecules/ContributionsTreemap/contributions-treemap.tsx
  lib/utils/color-utils.ts
  pages/lists/[listId]/activity.tsx
  stories/molecules/treemap-prototype/contributor-node.tsx
  stories/molecules/treemap-prototype/special-node.tsx
Labels: awaiting review

#1890 feat: issue support
  .github/workflows/issue.yml
Labels: requested changes

#1941 fix: list header misalignment now properly aligned
  components/ListHeader/list-header.tsx
  layouts/lists.tsx
Labels: awaiting review

#1909 fix: Fix horizontal padding /spacing on smaller screens for the Create New List form
  pages/hub/lists/new.tsx
Labels: awaiting review

#1915 refactor: show tootip indication for disabled CTA when repo limit is reached
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: awaiting review

#1962 fix: popover display issue of safari
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: requested changes

#1753 refactor: Rename the [filterName] query to more accurate naming in `/pages` routes
  components/molecules/ContributorHoverCard/contributor-hover-card.tsx
  components/molecules/FilterHeader/filter-header.tsx
  components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
  components/molecules/StackedAvatar/stacked-avatar.tsx
  components/molecules/TableHeader/table-header.tsx
  components/organisms/Contributors/contributors.tsx
  components/organisms/Repositories/repositories.tsx
  layouts/hub-page.tsx
  lib/hooks/api/useContributors.ts
  lib/hooks/api/useInsights.ts
  lib/hooks/api/usePullRequests.ts
  lib/hooks/api/useRepositories.ts
  lib/hooks/api/useRepositoryPullRequests.ts
  lib/hooks/useFilterPrefetch.ts
  lib/hooks/useNav.ts
  pages/[pageId]/[toolName].tsx
  pages/[pageId]/[toolName]/filter/[...selectedFilter].tsx
  pages/[pageId]/index.tsx
  pages/pages/[userOrg]/[pageId]/[toolName].tsx
  pages/pages/[userOrg]/[pageId]/[toolName]/filter/[...selectedFilter].tsx
Labels: awaiting review

#1992 feat: implement improved UX for non-connected users profile
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/molecules/InsightPageCard/insight-page-card.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/utils/copy-to-clipboard.ts
Labels: awaiting review

#2008 fix: now the error message in highlight form will alert assistive tech
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: awaiting review, a11y

#2012 fix: show contributors name and company in table
  components/atoms/Avatar/avatar-hover-card.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/DevProfile/dev-profile.tsx
Labels: awaiting review

#1993 fix: eslint issue by using `eslint-disable`
  .eslintrc.json
  components/ListHeader/list-header.tsx
  components/atoms/Avatar/avatar.tsx
  components/atoms/TopContributorCard/top-contributor-card.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/molecules/InsightHeader/insight-header.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  components/molecules/StackedAvatar/stacked-avatar.tsx
  components/organisms/StripeCheckoutButton/stripe-checkout-button.tsx
  generate-netlify-env.js
  lib/hooks/deleteHighlight.ts
  lib/hooks/fetchDevToBlogInfo.ts
  lib/hooks/fetchGithubIssueInfo.ts
  lib/hooks/fetchGithubOrgTeams.ts
  lib/hooks/fetchGithubPRInfo.ts
  lib/hooks/fetchGithubTeamMembers.ts
  lib/hooks/updateHighlight.ts
  lib/hooks/useFollowUser.ts
  lib/hooks/useInsightMembers.ts
  lib/hooks/useList.ts
  lib/hooks/useUserConnections.ts
  lib/hooks/useUserHighlightReactions.ts
  lib/utils/copy-to-clipboard.ts
  lib/utils/fetch-social-card.ts
  lib/utils/generate-blog-highlight-summary.ts
  lib/utils/generate-issue-highlight-summary.ts
  lib/utils/generate-pr-highlight-summary.ts
  lib/utils/github.ts
  lib/utils/public-api-fetcher.ts
  pages/_app.tsx
  pages/api/session.ts
  pages/hub/lists/find.tsx
  pages/hub/lists/index.tsx
  pages/hub/lists/new.tsx
  pages/start.tsx
  pages/user/[username]/index.tsx
Labels: requested changes
