Repository open-sauced/app, pull requests merged in 2023-09, with the labels that each got.

#1674 feat: add page layout and pages for lists overview, activity, and contributors
  components/ListHeader/list-header.tsx
  components/TabList/tab-list-item.tsx
  components/TabList/tab-list.tsx
  layouts/lists.tsx
  lib/hooks/useList.ts
  next-types.d.ts
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/contributors.tsx
  pages/lists/[listId]/index.tsx
  pages/lists/[listId]/overview.tsx
  pages/lists/index.tsx
Labels: awaiting review

#1643 feat: implement Live insights repo recommendations
  components/organisms/InsightPage/InsightPage.tsx
  components/organisms/RepositoriesCart/repositories-cart.tsx
  lib/hooks/useFetchOrgRecommendations.ts
  next-types.d.ts
Labels: awaiting review

#1659 fix: fixed Overlay button in footer
  components/organisms/Footer/footer.tsx
Labels: awaiting review

#1679 revert: list component changes on beta
  components/molecules/ListCard/list-card.tsx
  components/molecules/StackedAvatar/stacked-avatar.tsx
  next-types.d.ts
  stories/molecules/list-card.stories.tsx
Labels: awaiting review

#1686 ci: fix command for storybook build on release
  .github/workflows/storybook.yml
Labels: awaiting review

#1680 feat: add `ListNameHeader` component to design system
  components/ListHeader/list-header.tsx
  components/atoms/ListNameHeader/list-name-header.tsx
  stories/atoms/list-name-header.stories.tsx
  styles/globals.css
Labels: awaiting review

#1687 feat: add `ListCard` component to design system
  components/molecules/ListCard/list-card.tsx
  components/molecules/StackedAvatar/stacked-avatar.tsx
  next-types.d.ts
  stories/molecules/list-card.stories.tsx
Labels: 🎨 style

#1694 fix: handle `401` error on collaboration feature
  lib/hooks/useUserCollaborations.ts
Labels: awaiting review

#1688 feat: add `hacktoberfest` topic to dashboard filters
  img/hacktoberfest-icon.png
  img/topic-thumbnails/hacktoberfest.svg
  lib/utils/getInterestOptions.ts
  lib/utils/getTopicThumbnail.ts
  lib/utils/recommendations.ts
  stories/atoms/context-thumbnail.stories.tsx
Labels: requested changes

#1646 feat: new highlight creation popup (with highlight suggestions)
  components/atoms/Search/search.tsx
  components/atoms/TextInput/text-input.tsx
  components/atoms/Tooltip/tooltip.tsx
  components/molecules/CardRepoList/card-repo-list.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  components/molecules/PaginationGotoPage/pagination-goto-page.tsx
  npm-shrinkwrap.json
  package.json
  styles/globals.css
Labels: awaiting review

#1660 feat: Remove title input field from HighlightInputForm
  CHANGELOG.md
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: 💄 completed

#1682 feat: new insights tab layout for list feature
  components/atoms/Tabs/tabs.tsx
  components/molecules/ListCard/list-card.tsx
  layouts/hub-page.tsx
  layouts/hub.tsx
  layouts/lists.tsx
  lib/hooks/useList.ts
  next-types.d.ts
  pages/hub/index.tsx
  pages/hub/insights/index.tsx
  pages/hub/lists/index.tsx
  pages/hub/lists/new.tsx
Labels: awaiting review

#1714 chore: updated CODEOWNERS file
  .github/CODEOWNERS
Labels: chore

#1704 fix: opening someone's profile menu locks scrollbar and "shifts" header css
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: needs-approval

#1698 feat: create list feature
  components/atoms/FilterChip/filter-chip.tsx
  components/atoms/ListNameHeader/list-name-header.tsx
  components/atoms/ToggleSwitch/toggle-switch.tsx
  components/molecules/ComponentDateFilter/component-date-filter.tsx
  components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/DevProfile/dev-profile.tsx
  components/molecules/HubContributorsHeader/hub-contributors-header.tsx
  components/molecules/ListCard/list-card.tsx
  components/organisms/ContributorsTable/contributors-table.tsx
  components/organisms/Header/header.tsx
  layouts/hub-contributors.tsx
  lib/hooks/useFetchAllContributors.ts
  next-types.d.ts
  pages/hub/lists/new.tsx
  stories/atoms/filter-chip.stories.tsx
  tailwind.config.js
Labels: awaiting review

#1718 feat: add new`MultiSelect`component to design system
  components/atoms/Cmd/command.tsx
  components/atoms/Select/multi-select.tsx
  npm-shrinkwrap.json
  package.json
  stories/atoms/multi-select.stories.tsx
Labels: awaiting review

#1678 feat: add User Search
  components/molecules/AuthSection/auth-section.tsx
  components/organisms/SearchDialog/search-dialog.tsx
  components/organisms/TopNav/top-nav.tsx
  interfaces/global-state-types.ts
  lib/hooks/search-users.ts
  lib/hooks/useDebounceTerm.ts
  lib/hooks/useLockBody.ts
  lib/store/index.ts
  next-types.d.ts
  stories/organisms/search-dialog.stories.tsx
Labels: requested changes

#1732 feat: add `delete` functionality to list feature
  CHANGELOG.md
  components/molecules/ListCard/list-card.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  layouts/hub.tsx
  npm-shrinkwrap.json
  pages/hub/lists/index.tsx
Labels: awaiting review

#1761 fix: Date Selector not working on Highlight Creation
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: awaiting review

#1736 feat: add overview page for a list
  CHANGELOG.md
  components/molecules/HighlightCard/highlight-card.tsx
  components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
  lib/hooks/useListContributions.ts
  lib/hooks/useListStats.ts
  next-types.d.ts
  next.config.js
  pages/lists/[listId]/index.tsx
  pages/lists/[listId]/overview.tsx
Labels: awaiting review

#1739 feat: improve visibility of the follow cta on user profiles
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: awaiting review
