Repository open-sauced/app, pull requests merged in 2023-07, with the labels that each got.

#1327 fix: hide unnecessary scrollbar in profilepage
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: ready-to-merge

#1321 fix: update DevCard Contribution term to Repo
  components/molecules/DevCard/dev-card.tsx
  components/organisms/DevCardCarousel/stubData.ts
  pages/api/card.png.tsx
  pages/user/[username]/card.tsx
  stories/molecules/dev-card.stories.tsx
Labels: ready-to-merge

#1326 feat: add `UserCard` to feeds page
  components/atoms/UserCard/user-card.tsx
  components/molecules/TopUsersPanel/top-user-panel.tsx
  next-types.d.ts
  pages/feed/index.tsx
Labels: awaiting review

#1342 fix: ensure font color of selected interests pill changed is white
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: ready-to-merge

#1332 feat: implement newsletter submission functionality
  components/atoms/Button/button.tsx
  components/atoms/TextInput/text-input.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  lib/hooks/useUserHighlightReactions.ts
  pages/feed/index.tsx
Labels: ready-to-merge

#1331 feat: change position of visibility action component
  components/organisms/InsightPage/InsightPage.tsx
Labels: awaiting review

#1330 feat: add force login component to design system
  components/molecules/AuthContentWrapper/auth-content-wrapper.tsx
  stories/molecules/auth-content-wrapper.stories.tsx
Labels: ready-to-merge

#1337 feat: implement featured highlights list
  components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx
  components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
  components/molecules/NewsletterForm/newsletter-form.tsx
  lib/hooks/useFetchFeaturedHighlights.ts
  pages/feed/index.tsx
  stories/molecules/featured-highlights-panel.stories.tsx
Labels: awaiting review

#1360 style: text inputs colors were not consistent in the user settings page
  components/atoms/TextInput/text-input.tsx
Labels: awaiting review

#1347 feat: add top contributors panel to feeds page
  components/atoms/TopContributorCard/top-contributor-card.tsx
  components/atoms/TopUserCard/top-user-card.tsx
  components/molecules/TopContributorsPanel/top-contributors-panel.tsx
  components/molecules/TopUsersPanel/top-user-panel.tsx
  lib/hooks/useFetchTopContributors.ts
  lib/hooks/useFollowUser.ts
  pages/feed/index.tsx
  stories/atoms/top-user-card.stories.tsx
  stories/molecules/top-contributors-panel.stories.tsx
  stories/molecules/top-users-panel.stories.tsx
Labels: ready-to-merge

#1387 fix: Auto-Scroll Not Triggered Upon Clicking 'Next Page' in Highlight…
  pages/feed/index.tsx
Labels: needs-approval

#1370 feat: add discord link to user profile
  .gitignore
  components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
  lib/hooks/update-user.ts
  next-types.d.ts
Labels: awaiting review

#1409 fix: flash of "test content" while loading in dashboard page
  components/organisms/ToolsDisplay/tools-display.tsx
Labels: ready-to-merge, needs-approval

#1398 feat: add upgrade access button to user settings page
  components/organisms/Reports/reports.tsx
  components/organisms/StripeCheckoutButton/stripe-checkout-button.tsx
  components/organisms/UserSettingsPage/user-settings-page.tsx
Labels: requested changes

#1406 fix: factor `pullrequestLink` into `HighlightInput` form `isDivFocused` condition
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: ready-to-merge, needs-approval

#1390 feat: 404 page
  components/atoms/FullHeightContainer/full-height-container.tsx
  components/molecules/AuthSection/auth-section.tsx
  components/molecules/DevCard/dev-card.tsx
  components/molecules/TopContributorsPanel/top-contributors-panel.tsx
  components/organisms/DevCardWall/dev-card-wall.tsx
  img/icons/chevron-left.svg
  lib/hooks/useFetchTopContributors.ts
  pages/404.tsx
  pages/user/[username]/card.tsx
  stories/organisms/dev-card-wall.stories.tsx
Labels: ready-to-merge, needs-approval

#1403 fix: tab inconsistency in user profile matching the url
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: awaiting review

#1422 fix: misaligned chat close button icon
  styles/globals.css
Labels: awaiting review, ready-to-merge

#1420 fix: fixed bug on chatbot button overlay
  components/organisms/Footer/footer.tsx
Labels: awaiting review

#1419 fix: Deleted page button changed to delete highlight
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
Labels: tracking-issue

#1426 fix: show repo filters on initial `feeds` route visit
  pages/feed/index.tsx
Labels: awaiting review

#1429 style: add width and max width for created at in contributor-profile-tab
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: awaiting review, needs-approval

#1432 fix: contributor profile tab click state flicker
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/useContributorPullRequestsChart.ts
  pages/_app.tsx
Labels: ready-to-merge

#1435 fix: issue #1434 Improve Keyboard Accessibility for Notification Icon
  components/molecules/AuthSection/auth-section.tsx
Labels: awaiting review

#1436 fix: add navigation to improve accessibility
  components/organisms/TopNav/top-nav.tsx
Labels: awaiting review

#1443 feat: new contributor highlight card
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  lib/utils/github.ts
  stories/molecules/contributor-highlight-card.stories.tsx
Labels: needs-approval

#1437 fix: improve layout design for large screens #1231
  components/molecules/RepoRow/repo-row.tsx
  components/organisms/Repositories/repositories.tsx
Labels: needs-approval
