Repository open-sauced/app, pull requests merged in 2024-05, with the labels that each got.

#3449 test: added E2E tests for StarSearch logged out experience
  components/StarSearch/LoginModal.tsx
  e2e/star-search.spec.ts
  pages/star-search/index.tsx
Labels: testing, a11y

#3419 fix: prevent fetching contributor and repo insights for new workspaceId
  lib/hooks/api/useWorkspaceContributorInsights.ts
  lib/hooks/api/useWorkspaceRepositoryInsights.ts
Labels: needs-second-review

#3461 feat: added hover cards to StarSearch results that return links to GitHub users
  components/atoms/Avatar/avatar-hover-card.tsx
  pages/star-search/index.tsx
Labels: tier 3
