Repository open-sauced/app, pull requests merged in 2024-01, with the labels that each got.

#2443 fix: fixed regression where you couldn't view demo insights as a logged out user
  middleware.ts
Labels: needs-second-review

#2452 fix: hydration error in insights page
  layouts/hub-page.tsx
Labels: awaiting review

#2364 fix: now explore link is actively styled when neccessary
  components/organisms/TopNav/top-nav.tsx
Labels: awaiting review

#2416 feat: introduce application side nav
  components/Sidebar/app-sidebar.tsx
  components/Sidebar/sidebar-wrapper.tsx
  components/shared/feature-flagged.ts
  lib/hooks/useUserInsights.ts
  pages/_app.tsx
  pages/hub/insights/index.tsx
  pages/hub/lists/index.tsx
Labels: ready-to-merge

#2453 feat: add explainer tooltip to list stats card
  pages/lists/[listId]/overview.tsx
Labels: awaiting review

#2390 fix: added missing page numbers
  components/organisms/Contributors/contributors.tsx
  lib/hooks/api/useContributors.ts
Labels: requested changes

#2194 feat: add highlights to list pages
  components/Graphs/shared/contributor-type-filter.tsx
  components/TabList/tab-list.tsx
  components/atoms/EChartWrapper/echart-wrapper.tsx
  components/atoms/Radio/radio-group.tsx
  components/atoms/Search/search.tsx
  components/molecules/CardLineChart/card-line-chart.tsx
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/organisms/ContributorCard/contributor-card.tsx
  components/organisms/Repositories/repositories.tsx
  layouts/lists.tsx
  lib/hooks/useList.ts
  lib/utils/repo-to-filter-list.tsx
  next-types.d.ts
  npm-shrinkwrap.json
  package.json
  pages/feed/index.tsx
  pages/lists/[listId]/activity.tsx
  pages/lists/[listId]/add-contributors.tsx
  pages/lists/[listId]/highlights.tsx
Labels: awaiting review

#2412 fix: make emoji pick more accessible
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  styles/globals.css
Labels: 🐛 bug, requested changes, a11y

#2516 feat: update dashboard insights to use API v2 with histograms
  components/organisms/Dashboard/dashboard.tsx
  lib/hooks/api/useInsights.ts
  lib/hooks/api/usePullRequestsHistogram.ts
  next-types.d.ts
Labels: api-updates-needed

#2533 fix: Improved sidebar's UX and styling
  components/Workspaces/TrackedReposTable.tsx
  components/Workspaces/WorkspaceLayout.tsx
  components/shared/AppSidebar/AppSidebar.tsx
  components/shared/AppSidebar/InsightsPanel.tsx
  components/shared/AppSidebar/sidebar-menu-item.tsx
  pages/workspaces/new.tsx
  styles/globals.css
Labels: 🎨 style
