Repository open-sauced/app, pull requests merged in 2024-02, with the labels that each got.

#2611 fix: reduced the height of the chart wrapper that is making the butto…
  components/organisms/ContributorCard/contributor-card.tsx
Labels: awaiting review

#2587 fix: make a valid highlight link required to post a highlight
  components/molecules/HighlightInput/highlight-input-form.tsx
Labels: needs-approval

#2619 feat: make app sidebar collapsible
  components/Workspaces/WorkspaceLayout.tsx
  components/shared/AppSidebar/AppSidebar.tsx
Labels: needs design

#2609 fix: now disabled button that becomes enabled no longer causes a content layout shift
  components/atoms/Button/button.tsx
Labels: ready-to-merge

#2686 fix: now select repositories checkbox has label associated to it
  components/Workspaces/SearchReposTable.tsx
Labels: a11y

#2701 fix: now select all checkbox in contributors search table has a label
  components/Workspaces/SearchedContributorsTable.tsx
Labels: a11y
