Repository open-sauced/app, pull requests merged in 2024-03, with the labels that each got.

#2845 fix: add CTA for empty workspace insights page
  pages/workspaces/[workspaceId]/contributor-insights/index.tsx
  pages/workspaces/[workspaceId]/repository-insights/index.tsx
Labels: ready-to-merge

#2497 fix: Clear input after adding a repository to insight page
  components/organisms/InsightPage/InsightPage.tsx
Labels: awaiting review

#2936 fix: updated npm-shrinkwrap.json with new package name
  npm-shrinkwrap.json
Labels: merge conflicts

#2952 fix: remove duplicate layout on add-contributor in workspaces
  pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx
Labels: awaiting review

#2964 refactor: remove footer from workspaces
  components/Workspaces/WorkspaceLayout.tsx
Labels: awaiting review

#2582 feat(insights and lists): unify UX for insights and lists
  components/molecules/InsightRow/insight-row.tsx
  components/molecules/ListCard/list-card.tsx
  pages/hub/insights/index.tsx
Labels: merge conflicts

#2935 fix: redirect /hub/insights/new to login if not authenticated
  components/molecules/AuthContentWrapper/auth-content-wrapper.tsx
  next.config.js
  pages/workspaces/new.tsx
Labels: awaiting review

#2942 feat: `MetricCard` prototype
  components/Graphs/MetricCard.stories.tsx
  components/Graphs/MetricCard.tsx
  lib/hooks/api/useFetchMetricStats.ts
  pages/s/[org]/[repo]/index.tsx
Labels: repo-pages

#3040 feat: prototype Stars Chart for Repo pages
  components/Graphs/StarsChart.tsx
  lib/hooks/api/useFetchMetricStats.ts
  lib/utils/repo-page-utils.ts
  npm-shrinkwrap.json
  package.json
  pages/s/[org]/[repo]/index.tsx
Labels: merge conflicts

#3057 fix: disable create insight button on request
  components/Workspaces/TrackedContributorsTable.tsx
  components/Workspaces/TrackedReposTable.tsx
  pages/workspaces/[workspaceId]/contributor-insights/new.tsx
  pages/workspaces/[workspaceId]/repository-insights/new.tsx
Labels: awaiting review

#3065 fix: always show share button on contributor profiles
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: tier 4
