Repository open-sauced/app, pull requests merged in 2024-04, with the labels that each got.

#3068 feat: add oss.fyi links for invites
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Labels: needs-second-review, tier 4

#3063 feat: cumulative category for Stars Chart
  components/Graphs/MetricCard.tsx
  components/Graphs/StarsChart.tsx
  lib/utils/repo-page-utils.ts
  pages/s/[org]/[repo]/index.tsx
Labels: tier 2

#3088 feat: ForksChart for repo pages
  components/Graphs/ForksChart.stories.tsx
  components/Graphs/ForksChart.tsx
  lib/utils/repo-page-utils.ts
  next-types.d.ts
  pages/s/[org]/[repo]/index.tsx
Labels: repo-pages, tier 2

#3119 fix: remove login button from 404 page
  pages/404.tsx
Labels: tier 4

#3117 feat: created the OG image for repository pages
  components/Repositories/RepositoryOgImage.tsx
  netlify/edge-functions/repo-page-card.tsx
  pages/s/[org]/[repo]/index.tsx
  public/assets/og-images/repo-forked.png
Labels: tier 2

#3132 fix: now common OG image functions are in a utility file
  e2e/repo-page.spec.ts
  e2e/workspace-dashboard.spec.ts
  netlify/edge-functions/repo-page-card.tsx
  netlify/edge-functions/workspaces-card.tsx
  netlify/og-image-utils.ts
  playwright.config.ts
Labels: testing

#2534 fix: repos with long name partially stack
  components/atoms/Search/search.tsx
Labels: awaiting review

#3092 feat: matched Repository Insight edit page style to workspace UI
  lib/utils/workspace-utils.ts
  pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx
Labels: tier 3

#3109 feat: matched Contritbutor Insight edit page style to workspace UI
  components/ListHeader/list-header.tsx
  lib/utils/workspace-utils.ts
  pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx
  pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx
  pages/workspaces/[workspaceId]/contributor-insights/find.tsx
Labels: tier 3

#3125 feat: add range selection to contributor profile page
  components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
  components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
  components/molecules/PullRequestTable/pull-request-table.tsx
  components/organisms/ContributorCard/contributor-card.tsx
  components/organisms/ContributorProfilePage/contributor-profile-page.tsx
  components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
  lib/hooks/api/useContributorPullRequests.ts
  lib/hooks/useContributorPullRequestsChart.ts
  pages/user/[username]/index.tsx
Labels: needs-second-review, tier 3

#2963 refactor: remove `/hub` and `/pages` subfolder routing
  pages/hub/index.tsx
  pages/hub/insights/[insightId]/accept.tsx
  pages/hub/insights/[insightId]/edit.tsx
  pages/hub/insights/index.tsx
  pages/hub/insights/new.tsx
  pages/hub/lists/find.tsx
  pages/hub/lists/index.tsx
  pages/hub/lists/new.tsx
  pages/pages/[userOrg]/[pageId]/[toolName].tsx
  pages/pages/[userOrg]/[pageId]/[toolName]/filter/[...selectedFilter].tsx
Labels: needs-second-review

#3107 fix: pass selected repositories to new repository insight creation
  components/organisms/Repositories/repositories.tsx
  pages/workspaces/[workspaceId]/repository-insights/new.tsx
Labels: needs-second-review, tier 4

#3162 feat: basic implementation of StarSearch
  pages/starsearch.tsx
Labels: tier 1

#3204 feat: render markdown for `/starsearch` responses
  npm-shrinkwrap.json
  package.json
  pages/starsearch.tsx
Labels: tier 3

#3211 feat: styling `/starsearch`
  layouts/profile.tsx
  pages/starsearch.tsx
Labels: tier 3

#2555 feat: add support for blogpost from generic platforms
  components/molecules/ContributorHighlight/contributor-highlight-card.tsx
  components/molecules/GenericBlogOpenGraphImg/generic-blog-open-graph-img.tsx
  components/molecules/HighlightInput/highlight-input-form.tsx
  lib/utils/dev-to.test.ts
  lib/utils/dev-to.ts
  lib/utils/generate-dev-to-blog-highlight-summary.ts
  lib/utils/urls.ts
  npm-shrinkwrap.json
  package.json
  pages/api/fetchOGData.ts
Labels: tier 2

#3242 fix: now suggestion prompts run immediately
  pages/star-search/index.tsx
Labels: needs-second-review

#3199 feat: update stars and forks stats on repo pages
  components/Graphs/MetricCard.stories.tsx
  components/Graphs/MetricCard.tsx
  components/Workspaces/RepositoryStatCard.tsx
  next-types.d.ts
  pages/s/[org]/[repo]/index.tsx
Labels: tier 2

#3253 feat: implement PR and issue devstats to repo pages
  components/Workspaces/RepositoryStatCard.tsx
  next-types.d.ts
  pages/s/[org]/[repo]/index.tsx
Labels: tier 2

#3256 fix: use direct OpenGraph Image URLs on repository insight pages
  lib/utils/fetch-social-card.ts
  pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx
  pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx
  pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
Labels: needs-second-review

#3257 fix: fixed layout issues in StarSearch
  pages/star-search/index.tsx
Labels: tier 4

#3263 fix: now StarSearch link is in sidebar for smaller screens
  components/shared/AppSidebar/AppSidebar.tsx
Labels: tier 4

#3265 fix: now StarSearch input is not covered by vertical suggestions on small screens
  pages/star-search/index.tsx
Labels: tier 4

#3260 fix: now small screens show follow/unfollow on user profile
  components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Labels: medium-priority, tier 4

#3268 chore: added a name to job for Playwright GH action
  .github/workflows/playwright.yml
Labels: testing, tier 1

#3274 test: speed up server for playwright tests on CI
  .github/workflows/playwright.yml
  playwright.config.ts
Labels: testing

#3247 fix: remove filter prefetch and additional filters when searching by repository
  components/molecules/SuperlativeSelector/superlative-selector.tsx
  lib/hooks/api/useContributors.ts
  lib/hooks/api/useRepositoryPullRequests.ts
  lib/hooks/useFilterPrefetch.ts
Labels: tier 3
